### ISSUE TITLE
Where are the action keys?

### ISSUE THREAD

**Issue by MaxYari** [Greatness7/io_scene_mw#10]
Good evening. I can't find a way to access and edit action keys for the animations (anim name, start frame, stop frame e.t.c), Blender 3.4. Will appreciate a tip!

All the best,
Maksim.

**Comment by podvornyakva** [comment]
HAVOK is a proprietary. I do not think anybody will accomplish task of complete animation editing in Blender. Check animation toolchain on Nexus instead.

**Comment by MaxYari** [comment]
@podvornyakva Hi, thanks for the response, does it mean though that I can't edit those text keys using the blender plugin?

**Comment by podvornyakva** [comment]
Here is a article and rig. https://www.nexusmods.com/fallout4/mods/60005

**Comment by Greatness7** [comment]
The animation group timings are imported as [pose markers](https://docs.blender.org/manual/en/latest/animation/markers.html). You can view them in Blender's Action Editor interface, so long as you have **Show Pose Markers** enabled in the **Markers** menu. There is also a convenience UI available in the right side panel of the interface (this panel is collapsed by default, you can use `N` key to expand it).
