### ISSUE TITLE
Plugin is broken on ubuntu 22.04.

### ISSUE THREAD

**Issue by smirnov-danil** [Greatness7/io_scene_mw#11]
#### My system
```
~uname -a 
Linux machine 5.19.0-42-generic #43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 21 16:51:08 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

~ blender --version
Color management: using fallback mode for management
Color management: Error could not find role data role.
Blender 3.0.1

```
#### My steps
1) sudo apt-get install blender
2) download latest release
3) go to edit>prefs>addons, install addon
4) go to file>import>morrowind.nif

#### What do i expect to get:
.nif object is loaded, so i can work with it
#### What i actually get:
![изображение](https://github.com/Greatness7/io_scene_mw/assets/110029284/5fc9afe4-3f28-46df-ab8c-8b8b5f3ea21e)

**Comment by smirnov-danil** [comment]
also:
`~ python3 --version
Python 3.10.6
`

**Comment by Greatness7** [comment]
Seems the version of blender you got from `apt-get` is both incomplete and outdated. I recommend installing via the official downloads at [blender.org](https://www.blender.org/download/).
