### ISSUE TITLE
Cant Create morrow wind shaders error with python please help 

### ISSUE THREAD

**Issue by MrDutchMasterz** [Greatness7/io_scene_mw#12]
![blender error](https://github.com/Greatness7/io_scene_mw/assets/151265821/004f73bc-4265-4404-aae2-917469a3f94b)

I cant figure out what is causing this, did  reinstalls of blender, the addon, python etc countless times. I had this on my old pc with no issues now I went to install it on my new set up and it simply just doesn't work anymore. please help

**Comment by MrDutchMasterz** [comment]
figured it out.. im a fool. ### _**use blender 2.93 and it resolves everything.**_ hope this can help somebody else in the future

**Comment by MrDutchMasterz** [comment]
Figured it out.. use **blender 2.93 it fixes it**. hope this can help someone else

**Comment by Greatness7** [comment]
This was a conflict with Blender 4.0 specifically. It's now been fixed.
