### ISSUE TITLE
Exported .nif won't work in Construction Set / Nifscope

### ISSUE THREAD

**Issue by Orfey1** [Greatness7/io_scene_mw#14]
After exporting a custom creature with animation set from Blender using this addon, neither Construction Set or Nifscope can read the file. 
Construction set: Invalid NIF file directory.
Nifscope: The NIF file could not be read.
next block (181) does not start with a NiString

What do I do?

**Comment by Greatness7** [comment]
Can you upload the blend and nif files here?

**Comment by Orfey1** [comment]
Sure - thanks a lot for looking into it. There is a custom creature and a short test animation to check if it would work ingame at all. I've tried to export model without animations as just a static mesh, but I ended up having the same problem. I also get a message like this, but after clicking export once more it doesn't appear anymore:
![obraz](https://github.com/user-attachments/assets/89aab361-5c01-4e6c-80d5-102a43872253)

https://drive.google.com/drive/folders/1gWC6FthQmtNzXq6bhVH1dyvM1sV7k-WZ?usp=sharing

**Comment by Greatness7** [comment]
The plugin is not currently compatible with Blender 4.2, so that might be part of the issue.

**Comment by Orfey1** [comment]
I was trying to export the model out of Blender 2.93, but the result was the same. I started to think that maybe my model or rig is somehow faulty, but double checked if I can export files attached to tutorial I followed:
https://www.nexusmods.com/morrowind/mods/47736?tab=description
And those won't export at all, giving me the python traceback error.
Do you think it might be related to Blender version as well? I'll try 3.6 version of blender, because I've just seen on the plugin page it needs to be at least that or higher.

**Comment by Greatness7** [comment]
I recommend using Blender 4.1 for now.
