### ISSUE TITLE
Plugin broken in Blender 2.91 on Linux

### ISSUE THREAD

**Issue by andrew-wja** [Greatness7/io_scene_mw#5]
When trying to import any NIF file, verified working in NifSkope:

```
Python: Traceback (most recent call last):
  File "/home/andrew/.config/blender/2.91/scripts/addons/io_scene_mw/__init__.py", line 385, in execute
    from . import nif_import
  File "/home/andrew/.config/blender/2.91/scripts/addons/io_scene_mw/nif_import.py", line 12, in <module>
    from es3.utils import meshoptimizer
ImportError: cannot import name 'meshoptimizer' from 'es3.utils' (unknown location)

location: <unknown location>:-1
```

The source file `es3/util/meshoptimizer.py' appears to be missing...

**Comment by andrew-wja** [comment]
It works fine on windows (same Blender version)

**Comment by andrew-wja** [comment]
Could you add the source of this file instead of the cythonized object files?

**Comment by Greatness7** [comment]
The latest update should enable support for python 3.9 linux builds.

I've also made the meshoptimizer C++ binding code available [here](https://github.com/Greatness7/meshoptimizer_bindings).

**Comment by andrew-wja** [comment]
Thank you so much this works perfectly now! :D
