### ISSUE TITLE
Models are exported with bigger bounding boxes.

### ISSUE THREAD

**Issue by facu123lorenzo** [Greatness7/io_scene_mw#6]
When a model is exported from blender it shows a bigger bounding box in Construction Set.
![image](https://user-images.githubusercontent.com/28929192/105918547-d8541900-6012-11eb-939b-f813a0334ca3.png)
The problem persist even after transformations are applied.

**Comment by Greatness7** [comment]
I would need to see this nif to know for sure, but from what I recall of similar issues in the past it was a bug in the TESCS and not in the plugin itself.

**Comment by facu123lorenzo** [comment]
You're right, seems a bug in the CS, a very weird one. I just reloaded the editor and the bounding box is correct now, Thanks!
