### ISSUE TITLE
Error when trying to export my animation

### ISSUE THREAD

**Issue by RavenRST** [Greatness7/io_scene_mw#8]
Hello! Thanks for the great plugin!
When I try to export to .NIF a mesh with animation, that I made myself with 2 keyframes, I recieve the following error. 
![Traceback](https://user-images.githubusercontent.com/105810018/169100362-46228719-ce12-4350-859f-c32a8be00d26.png)

When exporting to .NIF a mesh without the "Extract keyframe date" function, it works fine.
If I first import .NIF from the original game into the Blender, then export it to .NIF, x.NIF and x.KF, then everything is fine, and models can be added to the game using CS, animations work in the game.
Please tell me what am I doing wrong. This is my first experience at making animations for Morrowind.
I am using Win7, Blender 2.83, tried io_scene_mw_0.8.65 and io_scene_mw_0.8.72

**Comment by Greatness7** [comment]
The `Extract Keyframe Data` option requires that you create some "text keys" (aka blender pose markers) for the game engine to control animation playback. It's only necessary if you're doing character animations or animations that need to be triggered from scripts.

The simplest example would be two keys, `Idle: Start` and `Idle: Stop`, specifying on which frames the `Idle` animation begins and ends.

You can create them in the action editor UI's right side panel (default key: N). 

[Example](https://cdn.discordapp.com/attachments/909403841676574720/974425494768476170/2022-05-12_17-27-42.mp4)

**Comment by RavenRST** [comment]
Thank you so much for your help! May God bless you! I was able to do the animation, and now there is a spinning portal portal in Oblivion
